name: ardent-pos
services:
- name: frontend
  source_dir: /frontend
  github:
    repo: mdYoungDOer/ardent-pos
    branch: main
    deploy_on_push: true
  build_command: npm install && npm run build
  output_dir: build
  routes:
  - path: /
  envs:
  - key: REACT_APP_API_URL
    scope: BUILD_TIME
    value: "${backend.PUBLIC_URL}"
  - key: REACT_APP_PAYSTACK_PUBLIC_KEY
    scope: BUILD_TIME
    type: SECRET

- name: backend
  source_dir: /backend
  github:
    repo: mdYoungDOer/ardent-pos
    branch: main
    deploy_on_push: true
  build_command: echo "No build needed"
  run_command: php -S 0.0.0.0:8080 -t backend simple-index.php
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: DB_HOST
    scope: RUN_TIME
    type: SECRET
  - key: DB_PORT
    scope: RUN_TIME
    value: "25060"
  - key: DB_NAME
    scope: RUN_TIME
    value: "ardent-pos-db"
  - key: DB_USER
    scope: RUN_TIME
    type: SECRET
  - key: DB_PASS
    scope: RUN_TIME
    type: SECRET
  - key: JWT_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: APP_URL
    scope: RUN_TIME
    value: "${APP_URL}"
  - key: CORS_ORIGIN
    scope: RUN_TIME
    value: "${APP_URL}"
  - key: PAYSTACK_PUBLIC_KEY
    scope: RUN_TIME
    type: SECRET
  - key: PAYSTACK_SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: SENDGRID_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: SENDGRID_FROM_EMAIL
    scope: RUN_TIME
    type: SECRET

databases:
- engine: PG
  name: ardent-pos-db
  num_nodes: 1
  size: db-s-1vcpu-1gb
  version: "14"
